# Generated by Django 5.2.1 on 2025-05-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_location_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_recognition/'),
        ),
    ]
