# Generated by Django 5.2.1 on 2025-05-19 17:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_face_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_face_image_path),
        ),
    ]
