# Generated by Django 5.2.1 on 2025-05-20 07:28

from django.db import migrations
import os
from django.conf import settings
import shutil


def move_face_images(apps, schema_editor):
    """
    Move existing face images from user_id based folders to email based folders
    """
    UserProfile = apps.get_model('accounts', 'UserProfile')
    User = apps.get_model('accounts', 'CustomUser')
    
    # Get all user profiles with face images
    profiles = UserProfile.objects.filter(face_image__isnull=False).exclude(face_image='')
    
    for profile in profiles:
        try:
            # Get current image path
            current_path = profile.face_image.path
            
            if not os.path.exists(current_path):
                continue
                
            # Get user email
            user = User.objects.get(id=profile.user_id)
            email = user.email
            safe_email = email.replace('@', '_at_').replace('.', '_dot_')
            
            # Create new directory if it doesn't exist
            new_dir = os.path.join(settings.MEDIA_ROOT, 'face_recognition', safe_email)
            os.makedirs(new_dir, exist_ok=True)
            
            # Get file name from current path
            file_name = os.path.basename(current_path)
            
            # New path
            new_path = os.path.join(new_dir, file_name)
            
            # Copy the file to new location
            shutil.copy2(current_path, new_path)
            
            # Update the database record
            new_relative_path = os.path.join('face_recognition', safe_email, file_name)
            profile.face_image = new_relative_path
            profile.save()
        except Exception as e:
            print(f"Error moving face image for user {profile.user_id}: {str(e)}")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_attendance_check_in_latitude_and_more'),
    ]

    operations = [
        migrations.RunPython(move_face_images, migrations.RunPython.noop),
    ]
