# Generated by Django 5.2.1 on 2025-05-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_update_face_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_absent',
            field=models.BooleanField(default=False, help_text='Marks whether this attendance is considered absent'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in_latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in_longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
    ]
