# Generated by Django 5.2.1 on 2025-06-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_attendance_is_absent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_supervisor',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a supervisor with admin-like permissions but cannot register or delete users'),
        ),
    ]