# Generated by Django 5.2.1 on 2025-07-26 14:36

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_is_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=accounts.models.user_face_images_path)),
                ('angle_index', models.IntegerField(help_text='Index representing the angle of the face image (0-9)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['angle_index'],
                'unique_together': {('user', 'angle_index')},
            },
        ),
    ]
