# Generated by Django 5.2.1 on 2025-07-30 04:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userfaceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfaceimage',
            name='image',
            field=models.ImageField(storage=accounts.models.SequentialFileStorage(), upload_to=accounts.models.user_face_images_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='face_image',
            field=models.ImageField(blank=True, null=True, storage=accounts.models.SequentialFileStorage(), upload_to=accounts.models.user_face_image_path),
        ),
    ]
